CREATE DATABASE IF NOT EXISTS comexport;

USE comexport;

CREATE TABLE IF NOT EXISTS role (
	Id integer NOT NULL AUTO_INCREMENT,
    Description varchar(255),
	CreatedAt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	UpdatedAt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	Enabled boolean,
    PRIMARY KEY (Id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS User (
	Id integer NOT NULL AUTO_INCREMENT,
	Id_role integer,
	Name varchar(255) NOT NULL,
	Email varchar(200) NOT NULL,
	Birthdate timestamp NOT NULL,
	CreatedAt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	UpdateAt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	Enabled boolean,
    primary key (Id),
	FOREIGN KEY (Id_role) REFERENCES role(Id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Reputation_User (
	Id integer NOT NULL AUTO_INCREMENT,
	Id_User integer NOT NULL,
    Score double,
	CreatedAt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UpdatedAt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	primary key (Id),
    FOREIGN KEY (Id_User) REFERENCES User(Id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Flags(
	Id integer NOT NULL AUTO_INCREMENT,
	Description varchar(255),
	CreatedAt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	UpdatedAt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	Enabled boolean,
    constraint primary key(Id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Question (
	Id integer NOT NULL AUTO_INCREMENT,
	Id_User integer NOT NULL,
	Id_Flag integer NOT NULL,
	Comment varchar(255),
	Resolved boolean,
	CreatedAt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	UpdatedAt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    primary key(Id),
	FOREIGN KEY (Id_User) REFERENCES User(Id),
	FOREIGN KEY (Id_Flag) REFERENCES Flags(Id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Answer(
	Id integer NOT NULL AUTO_INCREMENT,
	Id_User integer NOT NULL,
	Id_Question integer NOT NULL,
	Comment varchar(255),
	CreatedAt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	UpdatedAt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    primary key(Id),
	FOREIGN KEY (Id_User) REFERENCES User(Id),
	FOREIGN KEY (Id_Question) REFERENCES Question(Id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS Vote_Answer (
    Id integer NOT NULL AUTO_INCREMENT,
	Id_Question integer NOT NULL,
	Id_Answer integer NOT NULL,
	Id_User integer NOT NULL,
	Score double,
	CreatedAt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	UpdatedAt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	primary key(Id),
	FOREIGN KEY (Id_User) REFERENCES User(Id),
	FOREIGN KEY (Id_Question) REFERENCES Question(Id),
	FOREIGN KEY (Id_Answer) REFERENCES Answer(Id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;